import { useState, useEffect } from "react";
import { useFetcher } from "react-router";
import { useAtomValue } from "jotai";
import { gradientAtom } from "~/lib/atoms";
import { generateCSS } from "~/lib/gradient-engine";
import { generateGradientName, generateGradientTags } from "~/lib/auto-tag";
import { MarbleSvg } from "~/components/marble-canvas";

export function PublishButton() {
  const [open, setOpen] = useState(false);
  const state = useAtomValue(gradientAtom);
  const fetcher = useFetcher();
  const [name, setName] = useState("");
  const [tags, setTags] = useState("");
  const [autoGenerated, setAutoGenerated] = useState(false);

  // Auto-fill name and tags when dialog opens
  useEffect(() => {
    if (open && !autoGenerated) {
      setName(generateGradientName(state));
      setTags(generateGradientTags(state).join(", "));
      setAutoGenerated(true);
    }
    if (!open) {
      setAutoGenerated(false);
    }
  }, [open, state, autoGenerated]);

  const regenerate = () => {
    setName(generateGradientName(state));
    setTags(generateGradientTags(state).join(", "));
  };

  const isSubmitting = fetcher.state === "submitting";
  const isDone = fetcher.data?.ok;

  const handleSubmit = () => {
    fetcher.submit(
      {
        name: name || "Untitled",
        type: state.type,
        state: JSON.stringify(state),
        tags,
        previewCss: generateCSS(state),
      },
      { method: "post", action: "/api/publish" }
    );
  };

  if (isDone && open) {
    setTimeout(() => {
      setOpen(false);
      setName("");
      setTags("");
    }, 1500);
  }

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="shrink-0 px-4 py-2 rounded-xl border border-border text-sm font-medium text-text-dim hover:text-text hover:border-accent transition-all"
      >
        Publish
      </button>

      {open && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          <div className="absolute inset-0 bg-black/60" onClick={() => setOpen(false)} />

          <div className="relative bg-surface-2 border border-border rounded-2xl p-6 w-full max-w-md space-y-5">
            <div>
              <h2 className="text-lg font-semibold">Publish to Gallery</h2>
              <p className="text-xs text-text-dim mt-1">
                Share your {state.type} gradient with the community.
              </p>
            </div>

            {/* Preview strip */}
            <div
              className="h-20 rounded-xl overflow-hidden relative"
              style={
                state.type === "aura"
                  ? { backgroundColor: state.auraBgColor, backgroundImage: generateCSS(state) }
                  : state.type === "mesh"
                    ? { backgroundColor: state.meshBgColor, backgroundImage: generateCSS(state) }
                    : state.type === "marble"
                      ? {}
                      : { background: generateCSS(state) }
              }
            >
              {state.type === "marble" && <MarbleSvg state={state} className="rounded-xl" />}
            </div>

            {/* Name */}
            <div className="space-y-1.5">
              <div className="flex items-center justify-between">
                <label className="text-xs font-medium text-text-dim">Name</label>
                <button onClick={regenerate}
                  className="text-xs text-accent hover:text-accent-hover transition-all">
                  Regenerate
                </button>
              </div>
              <input
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g. Sunset Blaze"
                className="w-full bg-surface border border-border rounded-xl px-4 py-2.5 text-sm text-text placeholder:text-text-dim/40 focus:outline-none focus:border-accent"
              />
            </div>

            {/* Tags */}
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-text-dim">Tags</label>
              <div className="flex flex-wrap gap-1.5 mb-2">
                {tags.split(",").map((t) => t.trim()).filter(Boolean).map((tag) => (
                  <span key={tag} className="flex items-center gap-1 text-xs bg-surface-3 text-text-dim px-2 py-1 rounded-lg">
                    {tag}
                    <button
                      onClick={() => setTags(tags.split(",").map((t) => t.trim()).filter((t) => t !== tag).join(", "))}
                      className="text-text-dim/50 hover:text-red-400 leading-none"
                    >
                      &times;
                    </button>
                  </span>
                ))}
              </div>
              <input
                type="text"
                value={tags}
                onChange={(e) => setTags(e.target.value)}
                placeholder="e.g. dark, neon, vibrant"
                className="w-full bg-surface border border-border rounded-xl px-4 py-2.5 text-sm text-text placeholder:text-text-dim/40 focus:outline-none focus:border-accent"
              />
            </div>

            {/* Actions */}
            <div className="flex gap-3 pt-1">
              <button
                onClick={() => setOpen(false)}
                className="flex-1 py-2.5 rounded-xl border border-border text-sm text-text-dim hover:text-text transition-all"
              >
                Cancel
              </button>
              <button
                onClick={handleSubmit}
                disabled={isSubmitting || isDone}
                className={`flex-1 py-2.5 rounded-xl text-sm font-medium transition-all flex items-center justify-center gap-2 ${
                  isDone
                    ? "bg-surface-3 text-text-dim border border-border"
                    : "bg-accent text-black hover:bg-accent-hover disabled:opacity-50"
                }`}
              >
                {isDone ? (
                  <>
                    <svg className="w-4 h-4 text-green-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.5}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                    </svg>
                    Published
                  </>
                ) : isSubmitting ? (
                  <>
                    <svg className="w-4 h-4 animate-spin" viewBox="0 0 24 24" fill="none">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth={3} />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                    Publishing...
                  </>
                ) : (
                  "Publish"
                )}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
